In [1]:
import pandas as pd
import numpy as np

In [2]:
df_eurovision = pd.read_csv("datos/eurovision.csv")
df_eurovision.head()

,event,host_city,year,host_country,event_url,section,artist,song,artist_url,image_url,artist_country,country_emoji,running_order,total_points,rank,rank_ordinal,qualified,winner
0,Turin 2022,Turin,2022,Italy,https://eurovision.tv/event/turin-2022,first-semi-final,Kalush Orchestra,Stefania,https://eurovision.tv/participant/kalush-orche...,https://static.eurovision.tv/hb-cgi/images/963...,Ukraine,:flag_ua:,6.0,337.0,1.0,1st,True,False
1,Turin 2022,Turin,2022,Italy,https://eurovision.tv/event/turin-2022,first-semi-final,S10,De Diepte,https://eurovision.tv/participant/s10-22,https://static.eurovision.tv/hb-cgi/images/963...,Netherlands,:flag_nl:,8.0,221.0,2.0,2nd,True,False
2,Turin 2022,Turin,2022,Italy,https://eurovision.tv/event/turin-2022,first-semi-final,Amanda Georgiadi Tenfjord,Die Together,https://eurovision.tv/participant/amanda-georg...,https://static.eurovision.tv/hb-cgi/images/963...,Greece,:flag_gr:,15.0,211.0,3.0,3rd,True,False
3,Turin 2022,Turin,2022,Italy,https://eurovision.tv/event/turin-2022,first-semi-final,MARO,"Saudade, Saudade",https://eurovision.tv/participant/maro-22,https://static.eurovision.tv/hb-cgi/images/963...,Portugal,:flag_pt:,10.0,208.0,4.0,4th,True,False
4,Turin 2022,Turin,2022,Italy,https://eurovision.tv/event/turin-2022,first-semi-final,Intelligent Music Project,Intention,https://eurovision.tv/participant/intelligent-...,https://static.eurovision.tv/hb-cgi/images/963...,Bulgaria,:flag_bg:,7.0,29.0,16.0,16th,False,False

In [3]:
df_eurovision.shape

(2005, 18)

In [4]:
df_eurovision.dtypes

event              object
host_city          object
year                int64
host_country       object
event_url          object
section            object
artist             object
song               object
artist_url         object
image_url          object
artist_country     object
country_emoji      object
running_order     float64
total_points      float64
rank              float64
rank_ordinal       object
qualified            bool
winner               bool
dtype: object

In [5]:
df_eurovision.isnull().sum()

event                0
host_city            0
year                 0
host_country         0
event_url            0
section              0
artist               0
song                 1
artist_url           0
image_url         1046
artist_country       0
country_emoji        0
running_order        5
total_points        92
rank                41
rank_ordinal        41
qualified            0
winner               0
dtype: int64

In [6]:
df_eurovision.drop(["artist_url", "event_url", "country_emoji","image_url"], inplace = True, axis = 1)

In [7]:
df_eurovision.dropna(inplace=True)

In [8]:
df_eurovision.isnull().sum()

event             0
host_city         0
year              0
host_country      0
section           0
artist            0
song              0
artist_country    0
running_order     0
total_points      0
rank              0
rank_ordinal      0
qualified         0
winner            0
dtype: int64

In [9]:
df_eurovision.shape

(1913, 14)

In [10]:
df_eurovision["event"].unique()

array(['Turin 2022', 'Rotterdam 2021', 'Tel Aviv 2019', 'Lisbon 2018',
       'Kyiv 2017', 'Stockholm 2016', 'Vienna 2015', 'Copenhagen 2014',
       'Malmö 2013', 'Baku 2012', 'Düsseldorf 2011', 'Oslo 2010',
       'Moscow 2009', 'Belgrade 2008', 'Helsinki 2007', 'Athens 2006',
       'Kyiv 2005', 'Istanbul 2004', 'Riga 2003', 'Tallinn 2002',
       'Copenhagen 2001', 'Stockholm 2000', 'Jerusalem 1999',
       'Birmingham 1998', 'Dublin 1997', 'Oslo 1996', 'Dublin 1995',
       'Dublin 1994', 'Millstreet 1993', 'Malmö 1992', 'Rome 1991',
       'Zagreb 1990', 'Lausanne 1989', 'Dublin 1988', 'Brussels 1987',
       'Bergen 1986', 'Gothenburg 1985', 'Luxembourg 1984', 'Munich 1983',
       'Harrogate 1982', 'Dublin 1981', 'The Hague 1980',
       'Jerusalem 1979', 'Paris 1978', 'London 1977', 'The Hague 1976',
       'Stockholm 1975', 'Brighton 1974', 'Luxembourg 1973',
       'Edinburgh 1972', 'Dublin 1971', 'Amsterdam 1970', 'Madrid 1969',
       'London 1968', 'Vienna 1967', 'Luxembourg 1966', 'Naples 1965',
       'Copenhagen 1964', 'London 1963', 'Luxembourg 1962', 'Cannes 1961',
       'London 1960', 'Cannes 1959', 'Hilversum 1958', 'Frankfurt 1957'],
      dtype=object)

In [11]:
(df_eurovision.groupby("host_country")["year"].unique()).count()

26

In [12]:
df_eurovision.groupby("host_country")["song"].count()

host_country
Austria            76
Azerbaijan         62
Belgium            21
Denmark            92
Estonia            24
Finland            52
France             46
Germany            91
Greece             47
Ireland           152
Israel            103
Italy              95
Latvia             25
Luxembourg         64
Netherlands       117
Norway            102
Portugal           63
Russia             61
Serbia             63
Spain              16
Sweden            206
Switzerland        21
Turkey             45
Ukraine           111
United Kingdom    136
Yugoslavia         22
Name: song, dtype: int64

In [13]:
df_eurovision.head()

,event,host_city,year,host_country,section,artist,song,artist_country,running_order,total_points,rank,rank_ordinal,qualified,winner
0,Turin 2022,Turin,2022,Italy,first-semi-final,Kalush Orchestra,Stefania,Ukraine,6.0,337.0,1.0,1st,True,False
1,Turin 2022,Turin,2022,Italy,first-semi-final,S10,De Diepte,Netherlands,8.0,221.0,2.0,2nd,True,False
2,Turin 2022,Turin,2022,Italy,first-semi-final,Amanda Georgiadi Tenfjord,Die Together,Greece,15.0,211.0,3.0,3rd,True,False
3,Turin 2022,Turin,2022,Italy,first-semi-final,MARO,"Saudade, Saudade",Portugal,10.0,208.0,4.0,4th,True,False
4,Turin 2022,Turin,2022,Italy,first-semi-final,Intelligent Music Project,Intention,Bulgaria,7.0,29.0,16.0,16th,False,False

In [14]:
df_zero = df_eurovision[df_eurovision["total_points"] == 0.0]

In [15]:
df_bajos = df_eurovision[df_eurovision["total_points"] < 10.0]

In [16]:
df_bajos[df_bajos["artist_country"] == "Spain"]

,event,host_city,year,host_country,section,artist,song,artist_country,running_order,total_points,rank,rank_ordinal,qualified,winner
116,Rotterdam 2021,Rotterdam,2021,Netherlands,grand-final,Blas Cantó,Voy A Quedarme,Spain,13.0,6.0,24.0,24th,False,False
322,Kyiv 2017,Kyiv,2017,Ukraine,grand-final,Manel Navarro,Do It For Your Lover,Spain,16.0,5.0,26.0,26th,False,False
578,Malmö 2013,Malmö,2013,Sweden,grand-final,ESDM,Contigo Hasta El Final (With You Until The End),Spain,5.0,8.0,25.0,25th,False,False
1187,Jerusalem 1999,Jerusalem,1999,Israel,final,Lydia,No Quiero Escuchar,Spain,3.0,1.0,23.0,23rd,False,False
1788,Amsterdam 1970,Amsterdam,1970,Netherlands,final,Julio Iglesias,Gwendolyne,Spain,9.0,8.0,4.0,4th,False,False
1841,Vienna 1967,Vienna,1967,Austria,final,Raphael,Hablemos Del Amor,Spain,12.0,9.0,6.0,6th,False,False
1854,Luxembourg 1966,Luxembourg,1966,Luxembourg,final,Raphael,Yo Soy Aquél,Spain,11.0,9.0,7.0,7th,False,False
1883,Copenhagen 1964,Copenhagen,1964,Denmark,final,"Tim, Nelly and Tony",Caracola,Spain,16.0,1.0,12.0,12th,False,False
1903,London 1963,London,1963,United Kingdom,final,José Guardiola,Algo Prodigioso,Spain,12.0,2.0,12.0,12th,False,False
1946,Cannes 1961,Cannes,1961,France,final,Conchita Bautista,Estando Contigo,Spain,1.0,8.0,9.0,9th,False,False

In [17]:
df_eurovision["section"].unique()

array(['first-semi-final', 'second-semi-final', 'grand-final',
       'semi-final', 'final'], dtype=object)

In [18]:
df_eurovision_finales = df_eurovision[(df_eurovision["section"] == "grand-final") | (df_eurovision["section"] == "final")]

In [19]:
df_eurovision_finales["section"].unique()

array(['grand-final', 'final'], dtype=object)

In [20]:
df_eurovision_finales.head()

,event,host_city,year,host_country,section,artist,song,artist_country,running_order,total_points,rank,rank_ordinal,qualified,winner
35,Turin 2022,Turin,2022,Italy,grand-final,Sam Ryder,SPACE MAN,United Kingdom,22.0,466.0,2.0,2nd,False,False
36,Turin 2022,Turin,2022,Italy,grand-final,Chanel,SloMo,Spain,10.0,459.0,3.0,3rd,False,False
37,Turin 2022,Turin,2022,Italy,grand-final,Mahmood & BLANCO,Brividi,Italy,9.0,268.0,6.0,6th,False,False
38,Turin 2022,Turin,2022,Italy,grand-final,Alvan & Ahez,Fulenn,France,6.0,17.0,24.0,24th,False,False
39,Turin 2022,Turin,2022,Italy,grand-final,Malik Harris,Rockstars,Germany,13.0,6.0,25.0,25th,False,False

In [21]:
df_eurovision_finales.shape

(1325, 14)

In [22]:
df_eurovision_finales[["event", "host_city", "year"]].sample(15)

                event   host_city  year
1157  Copenhagen 2001  Copenhagen  2001
988       Athens 2006      Athens  2006
926     Helsinki 2007    Helsinki  2007
707   Düsseldorf 2011  Düsseldorf  2011
1623   Jerusalem 1979   Jerusalem  1979
1303      Dublin 1995      Dublin  1995
888     Belgrade 2008    Belgrade  2008
1568   Harrogate 1982   Harrogate  1982
1642       Paris 1978       Paris  1978
1810      Madrid 1969      Madrid  1969
218     Tel Aviv 2019    Tel Aviv  2019
1808      Madrid 1969      Madrid  1969
1383        Rome 1991        Rome  1991
1133     Tallinn 2002     Tallinn  2002
1527  Luxembourg 1984  Luxembourg  1984

In [23]:
df_eurovision_finales.drop("event", axis = 1, inplace = True)

/tmp/ipykernel_17867/2064548969.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eurovision_finales.drop("event", axis = 1, inplace = True)

In [24]:
df_eurovision_finales.head()

,host_city,year,host_country,section,artist,song,artist_country,running_order,total_points,rank,rank_ordinal,qualified,winner
35,Turin,2022,Italy,grand-final,Sam Ryder,SPACE MAN,United Kingdom,22.0,466.0,2.0,2nd,False,False
36,Turin,2022,Italy,grand-final,Chanel,SloMo,Spain,10.0,459.0,3.0,3rd,False,False
37,Turin,2022,Italy,grand-final,Mahmood & BLANCO,Brividi,Italy,9.0,268.0,6.0,6th,False,False
38,Turin,2022,Italy,grand-final,Alvan & Ahez,Fulenn,France,6.0,17.0,24.0,24th,False,False
39,Turin,2022,Italy,grand-final,Malik Harris,Rockstars,Germany,13.0,6.0,25.0,25th,False,False

In [25]:
df_eurovision_finales["qualified"].unique()

array([False])

In [26]:
df_eurovision_finales.drop("qualified", axis = 1, inplace = True)

/tmp/ipykernel_17867/3747518940.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eurovision_finales.drop("qualified", axis = 1, inplace = True)

In [27]:
df_eurovision_finales.reset_index(inplace= True, drop=True)

In [28]:
df_eurovision_finales.head()

,host_city,year,host_country,section,artist,song,artist_country,running_order,total_points,rank,rank_ordinal,winner
0,Turin,2022,Italy,grand-final,Sam Ryder,SPACE MAN,United Kingdom,22.0,466.0,2.0,2nd,False
1,Turin,2022,Italy,grand-final,Chanel,SloMo,Spain,10.0,459.0,3.0,3rd,False
2,Turin,2022,Italy,grand-final,Mahmood & BLANCO,Brividi,Italy,9.0,268.0,6.0,6th,False
3,Turin,2022,Italy,grand-final,Alvan & Ahez,Fulenn,France,6.0,17.0,24.0,24th,False
4,Turin,2022,Italy,grand-final,Malik Harris,Rockstars,Germany,13.0,6.0,25.0,25th,False

In [29]:
df_eurovision_finales["rank"].unique()

array([ 2.,  3.,  6., 24., 25.,  1., 11., 12., 13., 14., 15., 16., 17.,
       18., 19.,  4.,  5.,  7.,  8.,  9., 10., 20., 21., 22., 23., 26.,
       27.])

In [30]:
df_eurovision_finales["rank"] = df_eurovision_finales["rank"].astype("int64")

/tmp/ipykernel_17867/3513139148.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eurovision_finales["rank"] = df_eurovision_finales["rank"].astype("int64")

In [31]:
df_eurovision_finales.dtypes

host_city          object
year                int64
host_country       object
section            object
artist             object
song               object
artist_country     object
running_order     float64
total_points      float64
rank                int64
rank_ordinal       object
winner               bool
dtype: object

In [32]:
df_eurovision_finales["total_points"] = df_eurovision_finales["total_points"].astype("int64")

/tmp/ipykernel_17867/123888096.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eurovision_finales["total_points"] = df_eurovision_finales["total_points"].astype("int64")

In [33]:
df_eurovision_finales["running_order"] = df_eurovision_finales["running_order"].astype("int64")

/tmp/ipykernel_17867/344829491.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eurovision_finales["running_order"] = df_eurovision_finales["running_order"].astype("int64")

In [34]:
df_eurovision_finales.dtypes

host_city         object
year               int64
host_country      object
section           object
artist            object
song              object
artist_country    object
running_order      int64
total_points       int64
rank               int64
rank_ordinal      object
winner              bool
dtype: object

In [35]:
df_eurovision_finales.drop("rank_ordinal", axis = 1, inplace = True)

/tmp/ipykernel_17867/1935110481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eurovision_finales.drop("rank_ordinal", axis = 1, inplace = True)

In [36]:
df_eurovision_finales

,host_city,year,host_country,section,artist,song,artist_country,running_order,total_points,rank,winner
0,Turin,2022,Italy,grand-final,Sam Ryder,SPACE MAN,United Kingdom,22,466,2,False
1,Turin,2022,Italy,grand-final,Chanel,SloMo,Spain,10,459,3,False
2,Turin,2022,Italy,grand-final,Mahmood & BLANCO,Brividi,Italy,9,268,6,False
3,Turin,2022,Italy,grand-final,Alvan & Ahez,Fulenn,France,6,17,24,False
4,Turin,2022,Italy,grand-final,Malik Harris,Rockstars,Germany,13,6,25,False
...,...,...,...,...,...,...,...,...,...,...,...
1320,Frankfurt,1957,Germany,final,Bob Martin,"Wohin, Kleines Pony",Austria,5,3,10,False
1321,Frankfurt,1957,Germany,final,Nunzio Gallo,Corde Della Mia Chitarra,Italy,4,7,6,False
1322,Frankfurt,1957,Germany,final,Patricia Bredin,All,United Kingdom,3,6,7,False
1323,Frankfurt,1957,Germany,final,Danièle Dupré,Tant De Peine,Luxembourg,2,8,4,False
1324,Frankfurt,1957,Germany,final,Bobbejaan Schoepen,Straatdeuntje,Belgium,1,5,8,False

In [37]:
df_eurovision_finales.groupby("year")["total_points"].sum()

year
1957     100
1958     100
1959     110
1960     130
1961     160
        ...
2017    4872
2018    4988
2019    4756
2021    4524
2022    4640
Name: total_points, Length: 65, dtype: int64

In [38]:
df_eurovision_finales["total_points_per_year"] = df_eurovision_finales.groupby("year")["total_points"].transform("sum")

/tmp/ipykernel_17867/159264032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eurovision_finales["total_points_per_year"] = df_eurovision_finales.groupby("year")["total_points"].transform("sum")

In [39]:
df_eurovision_finales.tail()

,host_city,year,host_country,section,artist,song,artist_country,running_order,total_points,rank,winner,total_points_per_year
1320,Frankfurt,1957,Germany,final,Bob Martin,"Wohin, Kleines Pony",Austria,5,3,10,False,100
1321,Frankfurt,1957,Germany,final,Nunzio Gallo,Corde Della Mia Chitarra,Italy,4,7,6,False,100
1322,Frankfurt,1957,Germany,final,Patricia Bredin,All,United Kingdom,3,6,7,False,100
1323,Frankfurt,1957,Germany,final,Danièle Dupré,Tant De Peine,Luxembourg,2,8,4,False,100
1324,Frankfurt,1957,Germany,final,Bobbejaan Schoepen,Straatdeuntje,Belgium,1,5,8,False,100

In [40]:
df_eurovision_finales["percentage_points"] = round((df_eurovision_finales["total_points"]/df_eurovision_finales["total_points_per_year"])*100, 2)

/tmp/ipykernel_17867/498443695.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eurovision_finales["percentage_points"] = round((df_eurovision_finales["total_points"]/df_eurovision_finales["total_points_per_year"])*100, 2)

In [41]:
df_eurovision_losers = df_eurovision_finales.groupby("year")["rank"].max().reset_index()

In [42]:
df_eurovision_losers

    year  rank
0   1957    10
1   1958     9
2   1959    11
3   1960    13
4   1961    15
..   ...   ...
60  2017    26
61  2018    26
62  2019    26
63  2021    26
64  2022    25

[65 rows x 2 columns]

In [43]:
for year in df_eurovision_finales["year"]:
    if year in(df_eurovision_losers["year"]):
        if df_eurovision_losers["rank"] == df_eurovision_finales["rank"]:
            df_eurovision_finales["losers"] = True
        else:
            df_eurovision_finales["losers"] = False

In [44]:
df_eurovision_finales.head()

,host_city,year,host_country,section,artist,song,artist_country,running_order,total_points,rank,winner,total_points_per_year,percentage_points
0,Turin,2022,Italy,grand-final,Sam Ryder,SPACE MAN,United Kingdom,22,466,2,False,4640,10.04
1,Turin,2022,Italy,grand-final,Chanel,SloMo,Spain,10,459,3,False,4640,9.89
2,Turin,2022,Italy,grand-final,Mahmood & BLANCO,Brividi,Italy,9,268,6,False,4640,5.78
3,Turin,2022,Italy,grand-final,Alvan & Ahez,Fulenn,France,6,17,24,False,4640,0.37
4,Turin,2022,Italy,grand-final,Malik Harris,Rockstars,Germany,13,6,25,False,4640,0.13

In [45]:
df_eurovision_finales["winner"].value_counts()

False    1257
True       68
Name: winner, dtype: int64

In [46]:
for elem in df_eurovision_finales["winner"]:
    if elem == True:
        df_eurovision_finales["losers"] = False
    else:
        df_eurovision_finales["losers"] = True

/tmp/ipykernel_17867/3518169703.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eurovision_finales["losers"] = True
/tmp/ipykernel_17867/3518169703.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_eurovision_finales["losers"] = False

In [47]:
df_eurovision_finales["losers"].unique()

array([ True])

In [48]:
# for index, year in enumerate (df_eurovision_finales["year"]):
#     if year == df_eurovision_losers["year"][index]:
#         for index, ranking in enumerate (df_eurovision_finales["rank"]):
#                 if ranking == df_eurovision_losers["rank"]:
#                     df_eurovision_finales["losers"] = True
#                 else:
#                     df_eurovision_finales["losers"] = False

In [49]:
#df1 será df_eurovision_finales y df2 será df_eurovision_losers
# def crear_columna (col1, col2):
#     for year in col1:
#         if col2 == col2:
#             if df1["rank"] == df2["rank"]:
#                 return True
#             else:
#                 return False

In [50]:
# df_eurovision_finales["losers"] = df_eurovision_finales.apply(lambda data: crear_columna(df_eurovision_finales, df_eurovision_losers), axis = 1)

In [51]:
df_eurovision_finales.to_csv("datos/eurovision_clean.csv")